import React,{useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Activity,AlertTriangle,ArrowRight,BookOpen,CheckCircle2,ClipboardList,FlaskConical,HeartPulse,Info,ShieldCheck,Stethoscope,Users}from'lucide-react';
import'./styles.css';

const symptoms=[['discharge','Urethral/cervical or vaginal discharge'],['dysuria','Dysuria / burning urination'],['ulcer','Genital, oral or anal ulcer / blister'],['pelvic','Lower abdominal or pelvic pain'],['scrotal','Scrotal pain or swelling'],['rash','Generalized rash / palms or soles'],['rectal','Rectal pain, discharge or bleeding'],['throat','Sore throat after oral exposure'],['warts','Genital or perianal warts'],['none','No symptoms — screening visit']];
const exposures=[['vaginal','Vaginal'],['oral','Oral'],['anal','Anal'],['skin','Genital skin-to-skin'],['blood','Injecting equipment / blood']];
const sources=[
 {n:'Attached STI screening reference',d:'Baseline risk assessment, target populations, specimen-site selection and screening intervals.',u:'#baseline'},
 {n:'WHO STI guidelines',d:'2024 treatment updates and 2025 asymptomatic STI guidance.',u:'https://www.who.int/teams/global-hiv-hepatitis-and-stis-programmes/guidelines/stis-guidelines'},
 {n:'CDC STI Treatment Guidelines',d:'Detailed diagnostic, treatment, partner management and follow-up pathways.',u:'https://www.cdc.gov/std/treatment-guidelines/default.htm'},
 {n:'CDC screening recommendations',d:'Population and exposure-based STI screening recommendations.',u:'https://www.cdc.gov/std/treatment-guidelines/screening-recommendations.htm'},
 {n:'NACO STI/RTI services',d:'Indian program context and linkage to STI/RTI services.',u:'https://naco.mohfw.gov.in/division/sti-rti-services/'}
];
const empty={age:'',anatomy:'cervix',pregnant:false,hiv:'unknown',prep:false,newPartner:false,multiple:false,partnerSti:false,condomless:false,assault:false,sexWork:false,injecting:false,symptoms:[],exposures:[],duration:'',fever:false,severePain:false,vomiting:false,allergy:false};

function Button({children,onClick,kind='primary',disabled}){return <button className={'btn '+kind} onClick={onClick} disabled={disabled}>{children}</button>}
function Chip({on,children,onClick}){return <button type="button" className={'chip '+(on?'on':'')} onClick={onClick}>{on&&<CheckCircle2 size={15}/>} {children}</button>}
function Section({icon:Icon,title,children}){return <section className="card"><div className="cardTitle"><Icon size={20}/><h2>{title}</h2></div>{children}</section>}
function Field({label,children,hint}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}

function assess(p){
 const age=Number(p.age)||0, s=new Set(p.symptoms), x=new Set(p.exposures);
 const risks=p.newPartner||p.multiple||p.partnerSti||p.condomless||p.sexWork||p.assault;
 const red=p.fever||p.severePain||p.vomiting||(s.has('pelvic')&&p.pregnant)||(s.has('scrotal')&&p.severePain);
 const cats=[]; if(s.has('none')||!p.symptoms.length)cats.push('Asymptomatic screening'); if(s.has('discharge')||s.has('dysuria'))cats.push('Discharge / urethritis-cervicitis syndrome'); if(s.has('ulcer'))cats.push('Genital ulcer disease'); if(s.has('pelvic'))cats.push('Possible pelvic inflammatory disease'); if(s.has('scrotal'))cats.push('Possible epididymo-orchitis / acute scrotum'); if(s.has('rectal'))cats.push('Proctitis / proctocolitis syndrome'); if(s.has('warts'))cats.push('Anogenital wart syndrome'); if(s.has('rash'))cats.push('Possible secondary syphilis / systemic illness');
 const tests=[];
 const add=(name,specimen,why,priority='Recommended')=>{if(!tests.some(t=>t.name===name&&t.specimen===specimen))tests.push({name,specimen,why,priority})};
 if(s.has('discharge')||s.has('dysuria')||risks||p.prep||p.hiv==='positive'||(p.anatomy==='cervix'&&age>0&&age<25)){add('Chlamydia + gonorrhoea NAAT',x.has('vaginal')?(p.anatomy==='cervix'?'Self/clinician-collected vaginal swab':'First-catch urine'):'First-catch urine / vaginal swab','Core test; sample every exposed anatomic site.');}
 if(x.has('oral'))add('Gonorrhoea NAAT','Pharyngeal swab','Oral exposure; urine-only testing can miss infection.');
 if(x.has('anal')||s.has('rectal'))add('Gonorrhoea + chlamydia NAAT','Rectal swab','Rectal exposure or symptoms; consider LGV if proctitis.');
 if(s.has('ulcer')){add('Syphilis serology','Blood: treponemal + quantitative nontreponemal test','Ulcer evaluation and baseline titre.','Urgent');add('HSV PCR/NAAT','Fresh lesion swab','Preferred test for active vesicle/ulcer.','Urgent');}
 if(s.has('rash')||risks||p.pregnant||p.prep||p.hiv==='positive')add('Syphilis serology','Blood','Risk-based screening or compatible syndrome.');
 add('HIV Ag/Ab (4th generation)','Blood','Routine offer; add HIV RNA if very recent high-risk exposure or acute HIV suspected.');
 if(p.pregnant)add('HBsAg and anti-HCV','Blood','Antenatal screening; repeat according to risk/local policy.'); else if(risks||p.injecting||p.hiv==='positive'){add('Hepatitis B triple panel','Blood: HBsAg, anti-HBs, total anti-HBc','Assess infection and immunity.');add('Hepatitis C antibody ± RNA','Blood','Risk-based screening; RNA confirms active infection.');}
 if(s.has('discharge')&&p.anatomy==='cervix')add('Vaginitis testing','Vaginal sample: pH/microscopy or validated NAAT','Evaluate trichomoniasis, bacterial vaginosis and candidiasis.');
 if((s.has('discharge')||s.has('dysuria'))&&!p.pregnant)add('M. genitalium NAAT','First-catch urine / vaginal swab','Reserve for persistent or recurrent urethritis/cervicitis; resistance-guided therapy when available.','Conditional');
 const tx=[];
 if(s.has('discharge')||s.has('dysuria'))tx.push({title:'Urethritis/cervicitis pathway',text:'Collect NAAT first when feasible. Empiric therapy depends on examination, follow-up reliability and local resistance. If gonorrhoea cannot be excluded, use the locally recommended ceftriaxone regimen; add chlamydia treatment unless excluded. Pregnancy changes chlamydia drug choice.'});
 if(s.has('ulcer'))tx.push({title:'Genital ulcer pathway',text:'Treat presumptively when syphilis or first-episode herpes is clinically suspected, after specimens are obtained. Benzathine penicillin G is preferred for syphilis; stage and pregnancy determine regimen. Start oral antiviral promptly for first-episode genital herpes.'});
 if(s.has('pelvic'))tx.push({title:'Possible PID',text:'Perform pelvic examination and pregnancy test. Maintain a low threshold for empiric broad-spectrum outpatient therapy covering gonorrhoea, chlamydia and anaerobes; hospitalize for pregnancy, severe illness, tubo-ovarian abscess, surgical emergency, inability to tolerate oral therapy, or no response.'});
 if(s.has('scrotal'))tx.push({title:'Acute scrotal pain',text:'Urgently exclude torsion. If epididymitis is likely, select therapy by enteric versus sexually transmitted risk and obtain NAAT/culture as appropriate.'});
 if(s.has('rectal'))tx.push({title:'Proctitis pathway',text:'Examine and test rectal samples for gonorrhoea/chlamydia; test lesions for HSV and obtain syphilis/HIV tests. Severe proctitis with rectal chlamydia may require an LGV-duration doxycycline course.'});
 if(s.has('warts'))tx.push({title:'Anogenital warts',text:'Diagnosis is usually clinical. Choose patient-applied or clinician-administered therapy by site, burden, pregnancy and preference. Do not use podophyllotoxin/podofilox in pregnancy.'});
 if(!tx.length)tx.push({title:'No empiric treatment indicated from screening alone',text:'Test according to risk and exposure site, then use organism-, stage-, pregnancy- and resistance-directed treatment. Avoid treatment based only on this digital assessment.'});
 const follow=['No sex until the recommended interval has passed, symptoms resolve, and partners have been treated.','Offer partner notification/testing; follow local law and policy for expedited partner therapy.','Retest chlamydia, gonorrhoea and trichomoniasis at about 3 months because reinfection is common.','Document vaccines and offer hepatitis B and HPV vaccination when eligible.'];
 if(p.pregnant)follow.unshift('Pregnancy: arrange obstetric linkage. Chlamydia needs test-of-cure by NAAT about 4 weeks after treatment; repeat testing later if risk persists.');
 if(s.has('pelvic'))follow.unshift('Possible PID: clinical review within 72 hours; urgent escalation if not improving.');
 if(s.has('discharge')||s.has('dysuria'))follow.push('Persistent/recurrent symptoms: confirm adherence and reinfection status, then assess M. genitalium and T. vaginalis as appropriate.');
 return{cats,tests,tx,follow,red,risks};
}

function App(){const[p,setP]=useState(empty),[step,setStep]=useState(0); const a=useMemo(()=>assess(p),[p]); const toggle=(k,v)=>setP(q=>({...q,[k]:q[k].includes(v)?q[k].filter(z=>z!==v):[...q[k],v]}));
 return <><header><div className="brand"><div className="logo"><Activity/></div><div><b>STI Clinical Workbench</b><span>Structured screening & decision support</span></div></div><div className="badge"><ShieldCheck size={16}/> Clinician support · v1.0</div></header>
 <main><div className="hero"><p className="eyebrow">EVIDENCE-INFORMED CLINICAL PATHWAY</p><h1>From presentation to a safer<br/><em>next clinical step.</em></h1><p>Classify the presentation, map exposure sites, select tests, review treatment pathways and plan follow-up.</p><div className="notice"><Info size={18}/><span>For trained clinicians. This tool does not diagnose, replace examination, or override local protocols and antimicrobial-resistance guidance.</span></div></div>
 <nav>{['Patient & risk','Symptoms & exposure','Clinical plan'].map((n,i)=><button className={step===i?'active':''} onClick={()=>setStep(i)} key={n}><span>{i+1}</span>{n}</button>)}</nav>
 {step===0&&<div className="grid"><Section icon={Users} title="Patient profile"><div className="formGrid"><Field label="Age"><input type="number" min="0" placeholder="Years" value={p.age} onChange={e=>setP({...p,age:e.target.value})}/></Field><Field label="Relevant anatomy"><select value={p.anatomy} onChange={e=>setP({...p,anatomy:e.target.value})}><option value="cervix">Cervix / vagina</option><option value="penis">Penis / urethra</option><option value="other">Other / not specified</option></select></Field><Field label="HIV status"><select value={p.hiv} onChange={e=>setP({...p,hiv:e.target.value})}><option value="unknown">Unknown / negative</option><option value="positive">Living with HIV</option></select></Field></div><div className="checks"><label><input type="checkbox" checked={p.pregnant} onChange={e=>setP({...p,pregnant:e.target.checked})}/> Pregnant or possibly pregnant</label><label><input type="checkbox" checked={p.prep} onChange={e=>setP({...p,prep:e.target.checked})}/> Uses HIV PrEP</label><label><input type="checkbox" checked={p.allergy} onChange={e=>setP({...p,allergy:e.target.checked})}/> Significant antimicrobial allergy</label></div></Section><Section icon={ClipboardList} title="Risk assessment"><p className="muted">Select all that apply. Ask neutrally and confidentially.</p><div className="checks two">{[['newPartner','New partner'],['multiple','Multiple partners'],['partnerSti','Partner has STI/symptoms'],['condomless','Condomless sex'],['sexWork','Transactional sex'],['injecting','Shared injecting equipment'],['assault','Sexual assault / coercion']].map(([k,n])=><label key={k}><input type="checkbox" checked={p[k]} onChange={e=>setP({...p,[k]:e.target.checked})}/>{n}</label>)}</div></Section><div className="actions"><Button onClick={()=>setStep(1)}>Continue <ArrowRight size={17}/></Button></div></div>}
 {step===1&&<div className="grid"><Section icon={Stethoscope} title="Presentation"><p className="muted">Select symptoms currently present.</p><div className="chips">{symptoms.map(([k,n])=><Chip key={k} on={p.symptoms.includes(k)} onClick={()=>toggle('symptoms',k)}>{n}</Chip>)}</div><Field label="Duration"><input placeholder="e.g., 3 days" value={p.duration} onChange={e=>setP({...p,duration:e.target.value})}/></Field></Section><Section icon={HeartPulse} title="Exposure sites"><p className="muted">Test each exposed site; urine or genital testing alone can miss extragenital infection.</p><div className="chips">{exposures.map(([k,n])=><Chip key={k} on={p.exposures.includes(k)} onClick={()=>toggle('exposures',k)}>{n}</Chip>)}</div></Section><Section icon={AlertTriangle} title="Urgency screen"><div className="checks two">{[['fever','Fever / systemic illness'],['severePain','Severe pelvic or scrotal pain'],['vomiting','Vomiting / unable to take oral medication']].map(([k,n])=><label key={k}><input type="checkbox" checked={p[k]} onChange={e=>setP({...p,[k]:e.target.checked})}/>{n}</label>)}</div>{a.red&&<div className="danger">Urgent same-day in-person assessment is recommended. Exclude torsion, ectopic pregnancy, surgical abdomen, severe PID or disseminated infection as relevant.</div>}</Section><div className="actions"><Button kind="ghost" onClick={()=>setStep(0)}>Back</Button><Button onClick={()=>setStep(2)}>Generate clinical plan <ArrowRight size={17}/></Button></div></div>}
 {step===2&&<div className="results">{a.red&&<div className="urgent"><AlertTriangle/><div><b>Escalation flag</b><span>Arrange urgent same-day assessment; this pathway is not suitable for remote-only management.</span></div></div>}<Section icon={Activity} title="Clinical category"><div className="categoryList">{a.cats.length?a.cats.map(c=><span key={c}>{c}</span>):<span>Complete symptoms to classify</span>}</div></Section><Section icon={FlaskConical} title="Suggested tests"><div className="table">{a.tests.map((t,i)=><div className="tr" key={i}><div><b>{t.name}</b><span>{t.specimen}</span></div><p>{t.why}</p><i className={t.priority==='Urgent'?'red':''}>{t.priority}</i></div>)}</div><p className="foot">Timing and window periods matter. If acute HIV, early syphilis or HSV remains possible despite a negative result, repeat or add direct testing as clinically indicated.</p></Section><Section icon={Stethoscope} title="Treatment pathways"><div className="pathways">{a.tx.map((t,i)=><article key={i}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{t.title}</h3><p>{t.text}</p></div></article>)}</div>{p.allergy&&<div className="warn">Antimicrobial allergy selected: verify the exact drug, reaction and severity before selecting an alternative. Seek specialist advice for syphilis in pregnancy with penicillin allergy.</div>}</Section><Section icon={CheckCircle2} title="Follow-up & prevention"><ul>{a.follow.map(x=><li key={x}>{x}</li>)}</ul></Section><div className="actions"><Button kind="ghost" onClick={()=>setStep(1)}>Edit assessment</Button><Button onClick={()=>window.print()}>Print / save plan</Button></div></div>}
 <Section icon={BookOpen} title="Guideline library"><div className="sources">{sources.map(s=><a href={s.u} target={s.u.startsWith('http')?'_blank':undefined} key={s.n}><b>{s.n}</b><span>{s.d}</span><ArrowRight size={18}/></a>)}</div><p id="baseline" className="foot">The attached baseline document is used for screening logic. Treatment choices are framed as clinician-reviewed pathways because dosing depends on diagnosis, pregnancy, allergy, stage, weight, resistance and local/national guidance.</p></Section>
 </main><footer><span>STI Clinical Workbench</span><p>Privacy-first prototype: assessment data remains in this browser and is not stored or transmitted.</p></footer></>}
createRoot(document.getElementById('root')).render(<App/>);
